# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG and others
#
# SPDX-License-Identifier: Apache-2.0

name: Generate Gradle SBOM

on:
  workflow_run:
    workflows: [Release]
    types: [completed]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        default: 'main'
        required: true

env:
  JAVA_VERSION: '21'
  JAVA_DISTRO: 'temurin'
  PRODUCT_PATH: './'

permissions:
  contents: read

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    # STAGING: allow manual dispatch, which carries no workflow_run event.
    if: ${{ github.event_name == 'workflow_dispatch' ||
        github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.version }}

      - name: Setup Java SDK
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@8379f6a1328ee0e06e2bb424dadb7b159856a326 # v4.4.0

      - name: Generate sbom
        run: |
          gradle cyclonedxBom

      - name: Extract product version
        id: version
        shell: bash
        run: |
          VERSION="$(jq -r '.metadata.component.version' < ./${{ env.PRODUCT_PATH }}build/reports/bom.json)"
          echo "PROJECT_VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Product version is: $VERSION"

      - name: Upload sbom
        uses: eclipse-csi/workflows/upload-sbom@20e3c63807b2bd61b7f1a9f438e5ce588c054efc # main
        with:
          sbom-file: ${{ env.PRODUCT_PATH }}build/reports/bom.json
          product-name: 'arc'
          product-version: ${{ steps.version.outputs.PROJECT_VERSION }}
          staging: true
